ArgumentException: use system-supplied message if message is null (#25115)
Enable using a system-supplied message while also providing an argument/parameter name by passing in a null message. Made to match the behavior of FileNotFoundException.

Signed-off-by: dotnet-bot <dotnet-bot@microsoft.com>