Non-compilable method fixes and various fixes for generic methods
This change contains my previous non-compilable method fix slightly
polished based on Michal's PR feedback and a bunch of fixes for
generic methods, most notably fixing previously missing emission
of the instance entrypoint header table.

In the process I have slightly cleaned up the implementation of
the entrypoint tables: as these are now "summary nodes", no longer
state machines accumulating the methods during compilation, I have
removed the public "state machine" methods (Add). I have also moved
GetFixupBlob to MethodWithGCInfo so that it can be used from both
entrypoint tables.

I have included my recent fix for missing FrameInfos on x86 in a
slightly improved form - instead of forking all the code asking for
FrameInfos, I have modified its initialization so that, on x86,
where CorInfoImpl passes null, I generate a single-element
pseudo-frame info that lets me unify most of the related code.

Based on investigation of Michal's unit test I have also fixed
several places in method signature emission, token harvesting
and canonicalization. I have added Michal's sample as a new R2R
unit test (ReadyToRunTokens).

At this moment the test compiles and passes but apparently it JITs,
not actually uses, the two methods in the instance entrypoint table.
I assume that most likely there's a problem in the hashcode
calculation I intend to follow up on next.

As a side note for Simon, JITting the two offending methods reveals
there seems to be a bug in the ETW analysis; this is what the test
harness shows:

<pre>
Test execution PASSED

*** Jitted method analysis ***

White listed methods that were jitted (these don't count as test failures):
-None-

Methods that were jitted without a whitelist entry (test failure):
Int32].Compare(!0,class System.Object)
__Canon].Compare(!0,class System.Object)
Error: 2 methods were jitted.
</pre>

Thanks

Tomas