Fix incorrect MissingInteropDataException message
 Change Description:

     The missing exception type should be interface type instead of managed object type

     Before:

     System.Runtime.InteropServices.MissingInteropDataException:EETypeRva:0x00003a04[Windows.UI.Xaml.Visibility] is missing interop type marshalling data. To enable interop type marshalling data, add a MarshalObject directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965

     After:

     System.Runtime.InteropServices.MissingInteropDataException: Windows.Foundation.IReference`1<Windows.UI.Xaml.Visibility> is missing interop type marshalling data. To enable interop type marshalling data, add a MarshalObject directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965

[tfs-changeset: 1578958]