AggregateException: Use StringBuilder.AppendFormat (dotnet/coreclr#15747)
Use `AppendFormat(...)` instead of `Append(string.Format(...))` and
`AppendLine()` instead of `Append(Environment.NewLine)`.

Signed-off-by: dotnet-bot <dotnet-bot@microsoft.com>